version: '3.8'
services:
  fina:
    build:
      context: .
      dockerfile: Dockerfile
    image: fina:latest
    volumes:
      - ./:/workspace:cached
      - /workspace/node_modules
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    tty: true
    stdin_open: true
    command: ["/bin/bash", "-c", "while sleep 1000; do :; done"]
